import { CheckDouble, ExternalLink } from "@/icons/app"
import { StoryFn, StoryObj } from "@storybook/react-vite"
import { F0AiBanner, F0AiBannerProps } from "."
import { AiBannerSkeleton } from "./AiBannerInternal"

const meta = {
  title: "Experimental/Banners/F0AiBanner",
  component: F0AiBanner,
  parameters: {
    layout: "centered",
  },
  argTypes: {
    title: {
      control: "text",
      description: "The title displayed in the banner header",
    },
    onClose: {
      control: false,
      description: "Callback when the close button is clicked",
    },
    primaryAction: {
      control: "object",
      description: "Primary action button configuration",
    },
    secondaryAction: {
      control: "object",
      description: "Secondary action button configuration",
    },
    children: {
      control: "text",
      description: "Content displayed in the banner body",
    },
  },
  decorators: [
    (Story: StoryFn) => (
      <div className="w-96">
        <Story />
      </div>
    ),
  ],
}

export const Default: StoryObj<F0AiBannerProps> = {
  args: {
    title: "Approval suggested",
    onClose: () => alert("Banner closed"),
    primaryAction: {
      label: "Approve request",
      onClick: () => alert("Primary action clicked"),
      icon: CheckDouble,
    },
    secondaryAction: {
      label: "Set up smart rule",
      onClick: () => alert("Secondary action clicked"),
      icon: ExternalLink,
    },
    children: (
      <div>
        <p>
          Based on Elias&apos;s <u>team availability</u>, <u>time off policy</u>{" "}
          and <u>schedule</u> this request looks good to approve.
        </p>
        <br />
        <p>If you approve, Elias will have 2 holiday days remaining.</p>
      </div>
    ),
  },
}

export const WithoutActions: StoryObj<F0AiBannerProps> = {
  args: {
    title: "Information",
    onClose: () => alert("Banner closed"),
    children: (
      <div>
        <p>
          This is a simple informational banner without any action buttons.
          It&apos;s useful for displaying important messages or updates
          generated by AI.
        </p>
      </div>
    ),
  },
}

export const Skeleton: StoryObj = {
  render: () => <AiBannerSkeleton />,
}

export const SkeletonCompact: StoryObj = {
  render: () => <AiBannerSkeleton compact />,
}

export default meta
