export const famousEmployees = [
  {
    id: 1,
    firstName: "Albert",
    lastName: "Einstein",
    avatarUrl: "https://i.pravatar.cc/301",
  },
  {
    id: 2,
    firstName: "Marie",
    lastName: "Curie",
    avatarUrl: "https://i.pravatar.cc/302",
  },
  {
    id: 3,
    firstName: "Isaac",
    lastName: "Newton",
  },
  {
    id: 4,
    firstName: "Galileo",
    lastName: "Galilei",
  },
  {
    id: 5,
    firstName: "Leonardo",
    lastName: "da Vinci",
    avatarUrl: "https://i.pravatar.cc/305",
  },
  {
    id: 6,
    firstName: "Winston",
    lastName: "Churchill",
  },
  {
    id: 7,
    firstName: "Abraham",
    lastName: "Lincoln",
    avatarUrl: "https://i.pravatar.cc/307",
  },
  {
    id: 8,
    firstName: "George",
    lastName: "Washington",
    avatarUrl: "https://i.pravatar.cc/308",
  },
  {
    id: 9,
    firstName: "Thomas",
    lastName: "Edison",
    avatarUrl: "https://i.pravatar.cc/309",
  },
  {
    id: 10,
    firstName: "Nikola",
    lastName: "Tesla",
    avatarUrl: "https://i.pravatar.cc/310",
  },
  {
    id: 11,
    firstName: "Alexander",
    lastName: "Graham Bell",
    avatarUrl: "https://i.pravatar.cc/311",
  },
  {
    id: 12,
    firstName: "Martin Luther",
    lastName: "King",
    avatarUrl: "https://i.pravatar.cc/312",
  },
  {
    id: 13,
    firstName: "Mohandas",
    lastName: "Gandhi",
    avatarUrl: "https://i.pravatar.cc/313",
  },
  {
    id: 14,
    firstName: "Nelson",
    lastName: "Mandela",
    avatarUrl: "https://i.pravatar.cc/314",
  },
  {
    id: 15,
    firstName: "Pablo",
    lastName: "Picasso",
    avatarUrl: "https://i.pravatar.cc/315",
  },
  {
    id: 16,
    firstName: "Vincent",
    lastName: "van Gogh",
    avatarUrl: "https://i.pravatar.cc/316",
  },
  {
    id: 17,
    firstName: "Ludwig van",
    lastName: "Beethoven",
    avatarUrl: "https://i.pravatar.cc/317",
  },
  {
    id: 18,
    firstName: "Wolfgang Amadeus",
    lastName: "Mozart",
    avatarUrl: "https://i.pravatar.cc/318",
  },
  {
    id: 19,
    firstName: "William",
    lastName: "Shakespeare",
    avatarUrl: "https://i.pravatar.cc/319",
  },
  {
    id: 20,
    firstName: "Charles",
    lastName: "Dickens",
    avatarUrl: "https://i.pravatar.cc/320",
  },
  {
    id: 21,
    firstName: "Mark",
    lastName: "Twain",
    avatarUrl: "https://i.pravatar.cc/321",
  },
  {
    id: 22,
    firstName: "Jane",
    lastName: "Austen",
    avatarUrl: "https://i.pravatar.cc/322",
  },
  {
    id: 23,
    firstName: "Agatha",
    lastName: "Christie",
    avatarUrl: "https://i.pravatar.cc/323",
  },
  {
    id: 24,
    firstName: "Virginia",
    lastName: "Woolf",
    avatarUrl: "https://i.pravatar.cc/324",
  },
  {
    id: 25,
    firstName: "Oprah",
    lastName: "Winfrey",
    avatarUrl: "https://i.pravatar.cc/325",
  },
  {
    id: 26,
    firstName: "Elon",
    lastName: "Musk",
    avatarUrl: "https://i.pravatar.cc/326",
  },
  {
    id: 27,
    firstName: "Steve",
    lastName: "Jobs",
    avatarUrl: "https://i.pravatar.cc/327",
  },
  {
    id: 28,
    firstName: "Ada",
    lastName: "Lovelace",
    avatarUrl: "https://i.pravatar.cc/328",
  },
  {
    id: 29,
    firstName: "Grace",
    lastName: "Hopper",
    avatarUrl: "https://i.pravatar.cc/329",
  },
  {
    id: 30,
    firstName: "Coco",
    lastName: "Chanel",
  },
]
