import { IconType } from "@/components/F0Icon"
import * as ModuleIcons from "@/icons/modules"

export const modules = {
  "ai-reports": ModuleIcons.Reports,
  analytics: ModuleIcons.Reports,
  ats: ModuleIcons.Recruitment,
  benefits: ModuleIcons.Benefits,
  billing: ModuleIcons.Finance,
  calendar: ModuleIcons.Calendar,
  cards: ModuleIcons.Cards,
  "clock-in": ModuleIcons.ClockIn,
  company_attendance: ModuleIcons.TimeTracking,
  company_documents: ModuleIcons.Documents,
  company_projects: ModuleIcons.Projects,
  company_trainings: ModuleIcons.Trainings,
  compensations: ModuleIcons.Payroll,
  complaints: ModuleIcons.Complaints,
  discover: ModuleIcons.Discover,
  documents: ModuleIcons.Documents,
  employee_attendance: ModuleIcons.ClockIn,
  employees: ModuleIcons.Organization,
  engagement: ModuleIcons.Engagement,
  engagement_insights: ModuleIcons.Engagement,
  my_surveys: ModuleIcons.Engagement,
  "finance-accounting": ModuleIcons.Finance,
  "finance-sales": ModuleIcons.Sales,
  "finance-spending": ModuleIcons.Spending,
  "finance-treasury": ModuleIcons.Treasury,
  "finance-workspace": ModuleIcons.Reports,
  goals: ModuleIcons.Goals,
  home: ModuleIcons.Home,
  hub: ModuleIcons.Hub,
  it_management: ModuleIcons.ITManagement,
  kudos: ModuleIcons.Kudos,
  meetings: ModuleIcons.Meetings,
  my_benefits: ModuleIcons.Benefits,
  my_documents: ModuleIcons.MyDocuments,
  my_projects: ModuleIcons.Projects,
  my_spending: ModuleIcons.Spending,
  my_trainings: ModuleIcons.Trainings,
  "new-trainings": ModuleIcons.Trainings,
  notifications: ModuleIcons.Inbox,
  inbox: ModuleIcons.Inbox,
  overviews: ModuleIcons.Overviews,
  pages: ModuleIcons.Pages,
  payroll_bundle: ModuleIcons.Payroll,
  performance_v2: ModuleIcons.Performance,
  performance: ModuleIcons.Performance,
  playground: ModuleIcons.Home,
  processes: ModuleIcons.Workflows,
  profile: ModuleIcons.Profile,
  project_management: ModuleIcons.Projects,
  reports: ModuleIcons.Reports,
  settings: ModuleIcons.Settings,
  personal_settings: ModuleIcons.Settings,
  shift_management: ModuleIcons.Shifts,
  shifts: ModuleIcons.Shifts,
  social: ModuleIcons.Social,
  software: ModuleIcons.Software,
  space_control: ModuleIcons.Spaces,
  talent_analytics: ModuleIcons.Performance,
  tasks: ModuleIcons.Tasks,
  "time-tracking": ModuleIcons.TimeTracking,
  timeoff: ModuleIcons.TimeOff,
  workflows: ModuleIcons.Workflows,
} as const satisfies Record<string, IconType>

export type ModuleId = keyof typeof modules
