import * as ModuleIcons from "@/icons/modules"

export const modules = {
  benefits: ModuleIcons.Benefits,
  calendar: ModuleIcons.Calendar,
  cards: ModuleIcons.Cards,
  clockin: ModuleIcons.ClockIn,
  discover: ModuleIcons.Discover,
  documents: ModuleIcons.Documents,
  engagement: ModuleIcons.Engagement,
  finance: ModuleIcons.Finance,
  goals: ModuleIcons.Goals,
  home: ModuleIcons.Home,
  hub: ModuleIcons.Hub,
  inbox: ModuleIcons.Inbox,
  kudos: ModuleIcons.Kudos,
  mydocuments: ModuleIcons.MyDocuments,
  organization: ModuleIcons.Organization,
  overviews: ModuleIcons.Overviews,
  payroll: ModuleIcons.Payroll,
  performance: ModuleIcons.Performance,
  profile: ModuleIcons.Profile,
  projects: ModuleIcons.Projects,
  recruitment: ModuleIcons.Recruitment,
  reports: ModuleIcons.Reports,
  sales: ModuleIcons.Sales,
  settings: ModuleIcons.Settings,
  shifts: ModuleIcons.Shifts,
  social: ModuleIcons.Social,
  software: ModuleIcons.Software,
  spaces: ModuleIcons.Spaces,
  spending: ModuleIcons.Spending,
  tasks: ModuleIcons.Tasks,
  timeoff: ModuleIcons.TimeOff,
  timetracking: ModuleIcons.TimeTracking,
  trainings: ModuleIcons.Trainings,
  treasury: ModuleIcons.Treasury,
  workflows: ModuleIcons.Workflows,
} as const

export type ModuleId = keyof typeof modules
