// NOTE: This file was autogenerated. Don't edit it manually.
// More information here: .github/workflows/icons.yml

export type Tiny =
  | "alert"
  | "caret-down"
  | "caret-up"
  | "check"
  | "chevron-down"
  | "chevron-left"
  | "chevron-right"
  | "chevron-up"
  | "circle"
  | "clock"
  | "cross"
  | "person"
  | "question"
