// NOTE: This file was autogenerated. Don't edit it manually.
// More information here: .github/workflows/icons.yml

export const tiny = [
  "alert",
  "caret-down",
  "caret-up",
  "check",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "circle",
  "clock",
  "cross",
  "person",
  "question",
] as const

export type Tiny = (typeof tiny)[number]
